export const CRAWL_SCORE_ING = 'CRAWL_SCORE_ING';
export const CRAWL_SCRAPE_BEGIN = 'CRAWL_SCRAPE_BEGIN';
export const CRAWL_SCRAPE_SUCCESS = 'CRAWL_SCRAPE_SUCCESS';
export const CRAWL_SCRAPE_FAILURE = 'CRAWL_SCRAPE_FAILURE';
export const CRAWL_SCRAPE_DISMISS_ERROR = 'CRAWL_SCRAPE_DISMISS_ERROR';
